### ISSUE TITLE
Addition assignment?

### ISSUE THREAD

**Issue by tjvr** [livewires/you-win#13]
What's easier for beginners?

```js
foo.bar = foo.bar + 1
```

```js
foo.bar += 1
```

On the one hand, add-assign `+=` is more concise, and beginners type slowly.
However, they also take time to decide what to write, and maybe `x = x + 1` is an easier concept to grasp?

**Comment by heyitsmeuralex** [comment]
In CS class I've found that `+=` makes clear sense to most people. It's literally the typed equivalent of the Scratch `change %m.var by %n`, so it's easy to grasp.

**Comment by PullJosh** [comment]
> Maybe x = x + 1 is an easier concept to grasp?

I've actually found the opposite to be true. Beginners often have a difficult time understanding how a variable could be referenced while it's being assigned. In math, `a = a + 1` doesn't make much sense, because `a = a` is meant to hold. The fact that the variable is read before it is set can be surprisingly unintuitive for beginners.

**Comment by tjvr** [comment]
:+1:

Thanks, that's really helpful :D
